database:
  sqlite_path: "rss_links.db"
  rss_links_table_name: "rss_links"
  website_table_name: "rss_feed_websites"

  type: "cockroachdb"
  dbname: "rss_db"
  user: null
  password: null
  host: "localhost"
  port: "8080"

csv:
  rss_links: "rss_links.csv"
  rss_feed_websites: "rss_feed_websites.csv"

chunk_size: 5
